index:
    path: /
    controller: App\Controller\StoreFrontController::index
    methods: GET
#
# USER ROUTES
#
error_user:
    path: /user/error
    controller: App\Controller\StoreFrontController::errorPage
    methods: GET

show_user:
    path: /user/profile/{userId}
    controller: App\Controller\UserController::viewUser
    methods: GET
    requirements: 
        userId: '\d+' 

register_user_form:
    path: /user/register
    controller: App\Controller\UserController::showRegisterForm
    methods: GET

register_user:
    path: /user/api/register
    controller: App\Controller\UserController::registerUser
    methods: POST

list_user:
    path: /user/list
    controller: App\Controller\UserController::viewAllUsers
    methods: GET

delete_user:
    path: /user/api/delete/{userId}
    controller: App\Controller\UserController::removeUser
    methods: GET
    requirements: 
        userId: '\d+'

update_user_form:
    path: /user/update/{userId}
    controller: App\Controller\UserController::showUpdateForm
    methods: GET
    requirements: 
        userId: '\d+'
    
update_user:
    path: /user/api/update/{userId}
    controller: App\Controller\UserController::updateUser
    methods: POST
    requirements: 
        userId: '\d+'

login_user:
    path: /user/login
    controller: App\Controller\SecurityController::login

logout_user:
    path: /user/logout
    controller: App\Controller\SecurityController::logout

#
# STORE ROUTES
#
error_store:
    path: /store/error
    controller: App\Controller\StoreFrontController::errorPage
    methods: GET

show_product: 
    path: /store/order/{productId}
    controller: App\Controller\StoreFrontController::showProduct
    methods: GET
    requirements: 
        productId: '\d+' 

list_product:
    path: /store/list/{category}
    controller: App\Controller\StoreFrontController::listByCategory
    methods: GET

basket_product_form:
    path: /store/basket
    controller: App\Controller\StoreFrontController::showBasket
    methods: GET

add_product_to_basket:
    path: /store/basket/api/add/{productId}
    controller: App\Controller\StoreFrontController::addToBasket
    methods: GET
    requirements: 
        productId: '\d+'

increase_basket_count:
    path: /store/basket/api/increase/{productId}
    controller: App\Controller\StoreFrontController::increaseBasketItemCounter
    methods: GET
    requirements: 
        productId: '\d+'

decrease_basket_count:
    path: /store/basket/api/decrease/{productId}
    controller: App\Controller\StoreFrontController::decreaseBasketItemCounter
    methods: GET
    requirements: 
        productId: '\d+'

remove_from_basket:
    path: /store/basket/api/remove/{itemId}
    controller: App\Controller\StoreFrontController::removeFromBasket
    methods: GET
    requirements:
        productId: '\d+'

thank_you_page:
    path: /store/thank_you
    controller: App\Controller\StoreFrontController::showThankYouPage
    methods: GET
#
# ADMIN ROUTES
#
delete_product:
    path: /store/order/api/delete/{productId}
    controller: App\Controller\ProductController::deleteProduct
    methods: GET
    requirements: 
        productId: '\d+'

create_product_form:
    path: /store/order/create/{currCategory}
    controller: App\Controller\ProductController::showCreateForm
    methods: GET

create_product:
    path: /store/order/api/create
    controller: App\Controller\ProductController::createProduct
    methods: POST

update_product_form:
    path: /store/order/update/{productId}
    controller: App\Controller\ProductController::showUpdateForm
    methods: GET
    requirements: 
        productId: '\d+'

update_product:
    path: /store/order/api/update/{productId}
    controller: App\Controller\ProductController::updateProduct
    methods: POST 
    requirements: 
        productId: '\d+'